/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegalRouteRouteImport } from './routes/legal/route'
import { Route as LandingRouteRouteImport } from './routes/landing/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as LandingIndexRouteImport } from './routes/landing/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LandingAboutRouteImport } from './routes/landing/about'
import { Route as DashboardWorkoutsRouteImport } from './routes/dashboard/workouts'
import { Route as DashboardWorkoutBuilderRouteImport } from './routes/dashboard/workoutBuilder'
import { Route as DashboardMealsRouteImport } from './routes/dashboard/meals'
import { Route as DashboardMealBuilderRouteImport } from './routes/dashboard/mealBuilder'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetEmailSentRouteImport } from './routes/auth/reset-email-sent'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as DashboardWorkoutsIndexRouteImport } from './routes/dashboard/workouts.index'
import { Route as DashboardMealsIndexRouteImport } from './routes/dashboard/meals.index'
import { Route as DashboardWorkoutsWorkoutIdRouteImport } from './routes/dashboard/workouts.$workoutId'
import { Route as DashboardMealsMealIdRouteImport } from './routes/dashboard/meals.$mealId'
import { Route as AuthVerifyTokenRouteImport } from './routes/auth/verify.$token'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password.$token'

const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DashboardWorkoutsRoute = DashboardWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWorkoutBuilderRoute = DashboardWorkoutBuilderRouteImport.update({
  id: '/workoutBuilder',
  path: '/workoutBuilder',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMealsRoute = DashboardMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMealBuilderRoute = DashboardMealBuilderRouteImport.update({
  id: '/mealBuilder',
  path: '/mealBuilder',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetEmailSentRoute = AuthResetEmailSentRouteImport.update({
  id: '/reset-email-sent',
  path: '/reset-email-sent',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardWorkoutsIndexRoute = DashboardWorkoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardWorkoutsRoute,
} as any)
const DashboardMealsIndexRoute = DashboardMealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMealsRoute,
} as any)
const DashboardWorkoutsWorkoutIdRoute =
  DashboardWorkoutsWorkoutIdRouteImport.update({
    id: '/$workoutId',
    path: '/$workoutId',
    getParentRoute: () => DashboardWorkoutsRoute,
  } as any)
const DashboardMealsMealIdRoute = DashboardMealsMealIdRouteImport.update({
  id: '/$mealId',
  path: '/$mealId',
  getParentRoute: () => DashboardMealsRoute,
} as any)
const AuthVerifyTokenRoute = AuthVerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/landing': typeof LandingRouteRouteWithChildren
  '/legal': typeof LegalRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-email-sent': typeof AuthResetEmailSentRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/mealBuilder': typeof DashboardMealBuilderRoute
  '/dashboard/meals': typeof DashboardMealsRouteWithChildren
  '/dashboard/workoutBuilder': typeof DashboardWorkoutBuilderRoute
  '/dashboard/workouts': typeof DashboardWorkoutsRouteWithChildren
  '/landing/about': typeof LandingAboutRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify/$token': typeof AuthVerifyTokenRoute
  '/dashboard/meals/$mealId': typeof DashboardMealsMealIdRoute
  '/dashboard/workouts/$workoutId': typeof DashboardWorkoutsWorkoutIdRoute
  '/dashboard/meals/': typeof DashboardMealsIndexRoute
  '/dashboard/workouts/': typeof DashboardWorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-email-sent': typeof AuthResetEmailSentRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/mealBuilder': typeof DashboardMealBuilderRoute
  '/dashboard/workoutBuilder': typeof DashboardWorkoutBuilderRoute
  '/landing/about': typeof LandingAboutRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/landing': typeof LandingIndexRoute
  '/legal': typeof LegalIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify/$token': typeof AuthVerifyTokenRoute
  '/dashboard/meals/$mealId': typeof DashboardMealsMealIdRoute
  '/dashboard/workouts/$workoutId': typeof DashboardWorkoutsWorkoutIdRoute
  '/dashboard/meals': typeof DashboardMealsIndexRoute
  '/dashboard/workouts': typeof DashboardWorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/landing': typeof LandingRouteRouteWithChildren
  '/legal': typeof LegalRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-email-sent': typeof AuthResetEmailSentRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/mealBuilder': typeof DashboardMealBuilderRoute
  '/dashboard/meals': typeof DashboardMealsRouteWithChildren
  '/dashboard/workoutBuilder': typeof DashboardWorkoutBuilderRoute
  '/dashboard/workouts': typeof DashboardWorkoutsRouteWithChildren
  '/landing/about': typeof LandingAboutRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/landing/': typeof LandingIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify/$token': typeof AuthVerifyTokenRoute
  '/dashboard/meals/$mealId': typeof DashboardMealsMealIdRoute
  '/dashboard/workouts/$workoutId': typeof DashboardWorkoutsWorkoutIdRoute
  '/dashboard/meals/': typeof DashboardMealsIndexRoute
  '/dashboard/workouts/': typeof DashboardWorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/landing'
    | '/legal'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-email-sent'
    | '/auth/signup'
    | '/dashboard/mealBuilder'
    | '/dashboard/meals'
    | '/dashboard/workoutBuilder'
    | '/dashboard/workouts'
    | '/landing/about'
    | '/legal/privacy'
    | '/legal/terms'
    | '/auth/'
    | '/dashboard/'
    | '/landing/'
    | '/legal/'
    | '/auth/reset-password/$token'
    | '/auth/verify/$token'
    | '/dashboard/meals/$mealId'
    | '/dashboard/workouts/$workoutId'
    | '/dashboard/meals/'
    | '/dashboard/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-email-sent'
    | '/auth/signup'
    | '/dashboard/mealBuilder'
    | '/dashboard/workoutBuilder'
    | '/landing/about'
    | '/legal/privacy'
    | '/legal/terms'
    | '/auth'
    | '/dashboard'
    | '/landing'
    | '/legal'
    | '/auth/reset-password/$token'
    | '/auth/verify/$token'
    | '/dashboard/meals/$mealId'
    | '/dashboard/workouts/$workoutId'
    | '/dashboard/meals'
    | '/dashboard/workouts'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/landing'
    | '/legal'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-email-sent'
    | '/auth/signup'
    | '/dashboard/mealBuilder'
    | '/dashboard/meals'
    | '/dashboard/workoutBuilder'
    | '/dashboard/workouts'
    | '/landing/about'
    | '/legal/privacy'
    | '/legal/terms'
    | '/auth/'
    | '/dashboard/'
    | '/landing/'
    | '/legal/'
    | '/auth/reset-password/$token'
    | '/auth/verify/$token'
    | '/dashboard/meals/$mealId'
    | '/dashboard/workouts/$workoutId'
    | '/dashboard/meals/'
    | '/dashboard/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/landing/': {
      id: '/landing/'
      path: '/'
      fullPath: '/landing/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/landing/about': {
      id: '/landing/about'
      path: '/about'
      fullPath: '/landing/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/dashboard/workouts': {
      id: '/dashboard/workouts'
      path: '/workouts'
      fullPath: '/dashboard/workouts'
      preLoaderRoute: typeof DashboardWorkoutsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/workoutBuilder': {
      id: '/dashboard/workoutBuilder'
      path: '/workoutBuilder'
      fullPath: '/dashboard/workoutBuilder'
      preLoaderRoute: typeof DashboardWorkoutBuilderRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/meals': {
      id: '/dashboard/meals'
      path: '/meals'
      fullPath: '/dashboard/meals'
      preLoaderRoute: typeof DashboardMealsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/mealBuilder': {
      id: '/dashboard/mealBuilder'
      path: '/mealBuilder'
      fullPath: '/dashboard/mealBuilder'
      preLoaderRoute: typeof DashboardMealBuilderRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-email-sent': {
      id: '/auth/reset-email-sent'
      path: '/reset-email-sent'
      fullPath: '/auth/reset-email-sent'
      preLoaderRoute: typeof AuthResetEmailSentRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/workouts/': {
      id: '/dashboard/workouts/'
      path: '/'
      fullPath: '/dashboard/workouts/'
      preLoaderRoute: typeof DashboardWorkoutsIndexRouteImport
      parentRoute: typeof DashboardWorkoutsRoute
    }
    '/dashboard/meals/': {
      id: '/dashboard/meals/'
      path: '/'
      fullPath: '/dashboard/meals/'
      preLoaderRoute: typeof DashboardMealsIndexRouteImport
      parentRoute: typeof DashboardMealsRoute
    }
    '/dashboard/workouts/$workoutId': {
      id: '/dashboard/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/dashboard/workouts/$workoutId'
      preLoaderRoute: typeof DashboardWorkoutsWorkoutIdRouteImport
      parentRoute: typeof DashboardWorkoutsRoute
    }
    '/dashboard/meals/$mealId': {
      id: '/dashboard/meals/$mealId'
      path: '/$mealId'
      fullPath: '/dashboard/meals/$mealId'
      preLoaderRoute: typeof DashboardMealsMealIdRouteImport
      parentRoute: typeof DashboardMealsRoute
    }
    '/auth/verify/$token': {
      id: '/auth/verify/$token'
      path: '/verify/$token'
      fullPath: '/auth/verify/$token'
      preLoaderRoute: typeof AuthVerifyTokenRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetEmailSentRoute: typeof AuthResetEmailSentRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
  AuthVerifyTokenRoute: typeof AuthVerifyTokenRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetEmailSentRoute: AuthResetEmailSentRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
  AuthVerifyTokenRoute: AuthVerifyTokenRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardMealsRouteChildren {
  DashboardMealsMealIdRoute: typeof DashboardMealsMealIdRoute
  DashboardMealsIndexRoute: typeof DashboardMealsIndexRoute
}

const DashboardMealsRouteChildren: DashboardMealsRouteChildren = {
  DashboardMealsMealIdRoute: DashboardMealsMealIdRoute,
  DashboardMealsIndexRoute: DashboardMealsIndexRoute,
}

const DashboardMealsRouteWithChildren = DashboardMealsRoute._addFileChildren(
  DashboardMealsRouteChildren,
)

interface DashboardWorkoutsRouteChildren {
  DashboardWorkoutsWorkoutIdRoute: typeof DashboardWorkoutsWorkoutIdRoute
  DashboardWorkoutsIndexRoute: typeof DashboardWorkoutsIndexRoute
}

const DashboardWorkoutsRouteChildren: DashboardWorkoutsRouteChildren = {
  DashboardWorkoutsWorkoutIdRoute: DashboardWorkoutsWorkoutIdRoute,
  DashboardWorkoutsIndexRoute: DashboardWorkoutsIndexRoute,
}

const DashboardWorkoutsRouteWithChildren =
  DashboardWorkoutsRoute._addFileChildren(DashboardWorkoutsRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardMealBuilderRoute: typeof DashboardMealBuilderRoute
  DashboardMealsRoute: typeof DashboardMealsRouteWithChildren
  DashboardWorkoutBuilderRoute: typeof DashboardWorkoutBuilderRoute
  DashboardWorkoutsRoute: typeof DashboardWorkoutsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardMealBuilderRoute: DashboardMealBuilderRoute,
  DashboardMealsRoute: DashboardMealsRouteWithChildren,
  DashboardWorkoutBuilderRoute: DashboardWorkoutBuilderRoute,
  DashboardWorkoutsRoute: DashboardWorkoutsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingAboutRoute: typeof LandingAboutRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingAboutRoute: LandingAboutRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface LegalRouteRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  LegalRouteRoute: LegalRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
